import { ColumnKey, FormFieldType } from "../enums";
import { ColumnDef } from "../types";

export const accountTransferSchema: ColumnDef[] = [
  {
    label: "З рахунку",
    name: "fromId",
    columnType: ColumnKey.ACCOUNT,
    formType: FormFieldType.ACCOUNT_SELECT,
    isFormField: true,
    isRequired: true,
  },
  {
    label: "На рахунок",
    name: "toId",
    columnType: ColumnKey.ACCOUNT,
    formType: FormFieldType.ACCOUNT_SELECT,
    isFormField: true,
    isRequired: true,
  },
  {
    label: "Сума переказу",
    name: "sum",
    columnType: ColumnKey.SUM,
    formType: FormFieldType.NUMBER,
    placeholder: "0.00",
    labelPlacement: "outside",
    isFormField: true,
    isRequired: true,
  },
  {
    label: "Баланс рахунку відправника (до)",
    name: "fromOldSum",
    columnType: ColumnKey.SUM,
    formType: FormFieldType.NUMBER,
    placeholder: "0.00",
    labelPlacement: "outside",
    isFormField: true,
    isRequired: true,
  },
  {
    label: "Баланс рахунку отримувача (до)",
    name: "toOldSum",
    columnType: ColumnKey.SUM,
    formType: FormFieldType.NUMBER,
    placeholder: "0.00",
    labelPlacement: "outside",
    isFormField: true,
    isRequired: true,
  },
  {
    label: "Баланс рахунку відправника (після)",
    name: "fromNewSum",
    columnType: ColumnKey.SUM,
    formType: FormFieldType.NUMBER,
    placeholder: "0.00",
    labelPlacement: "outside",
    isFormField: true,
    isRequired: true,
  },
  {
    label: "Баланс рахунку отримувача (після)",
    name: "toNewSum",
    columnType: ColumnKey.SUM,
    formType: FormFieldType.NUMBER,
    placeholder: "0.00",
    labelPlacement: "outside",
    isFormField: true,
    isRequired: true,
  },
];
