export enum AppPath {
  ADMIN = "/admin",
  STATS = "/admin/stats",
  ACCOUNTS = "/admin/accounts",
  ACCOUNT_TRANSFERS = "/admin/account-transfers",
  CATEGORIES = "/admin/categories",
  ADMIN_PRODUCTS = "/admin/products",
  HOME = "/",
  HOME_HERO = "/#hero",
  HOME_SERVICES = "/#services",
  HOME_MASTERS = "/#masters",
  HOME_GALLERY = "/#gallery",
  HOME_ABOUT = "/#about",
  HOME_CONTACTS = "/#contacts",
  LOGIN = "/login",
}
