export enum SEO {
  TITLE = "Rowdy Barbershop | Чоловіча перукарня в місті Запоріжжя",
  DESCRIPTION = "Rowdy Barbershop ✄ Барбершоп в місті Запоріжжя ✄ Запишись онлайн вже сьогодні! ✄ Чоловіча перукарня в Запоріжжі ☎️ 066 337 27 63 ✄ Професійні стрижки, гоління та багато іншого",
  EMAIL = "rowdy.barbershop@gmail.com",
  PHONE_NUMBER_1 = "+38 (066) 337 27 63",
  PHONE_NUMBER_2 = "+38 (068) 771 03 37",
  LOCALE = "uk_UA",
  APLICATION_NAME = "Rowdy Barbershop",
  AUTHOR_NAME = "Anton Bohachuk",
  AUTHOR_URL = "https://antoxa566.github.io/resume/",
  KEYWORDS = "барбершоп, запорожье, запорожья, запоріжжя, запоріжжі, зп, перукарня, бороды, стрижка, стрижки, цены, мужские, барбер, сталеваров, победы, шоп, чоловіча, стрижек, мужская, парикмахерская, barbershop, barber, shop",
  GENERATOR = "Next.js",
  PUBLISHER = "Vercel",
  COUNTRY_NAME = "Ukraine",
  OG_TYPE = "website",
}
